[package]
edition = "2024"
name = "rustwasm-decoder-testbed"
version = "0.1.0"

[dependencies]
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
wasm-bindgen = "0.2.105"
zip = {version = "5.1.1", default-features = false, features = ["deflate"]}
